### ISSUE TITLE
Share scraped dataset

### ISSUE THREAD

**Issue by Keith-Hon** [ayaka14732/lihkg-scraper#1]
Is it possible for you to upload the crawled dataset?

**Comment by ayaka14732** [comment]
https://pastebin.com/zU2gqKH6

**Comment by shivanraptor** [comment]
Oops, it's expired :(

**Comment by ayaka14732** [comment]
https://pastebin.com/x7NFK3yv

**Comment by kirbystudy** [comment]
it's expired

**Comment by baiyongrui** [comment]
Hello, I saw two of the url are expired. May you share the dataset again? Thanks

**Comment by ayaka14732** [comment]
I think someone has uploaded it on Hugging Face: https://huggingface.co/datasets/AlienKevin/LIHKG
